services:
  server:
    build:
      context: ./apps/server
      dockerfile: Dockerfile
    container_name: go_starter_template_server
    ports:
      - "8080:8080"
    env_file:
      - ./apps/server/.env
    depends_on:
      - postgres
      - redis

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: go_starter_template_web
    ports:
      - "5173:5173"
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  postgres:
    image: postgres:latest
    container_name: go_starter_template_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: go_starter_template_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
